name: gstcream-clippy-docs

# Only run the CI on PR to master.
on:
  pull_request:
    branches:
      - master
  
  push:
    branches: [ "ci" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run docs
      run: |
        cd gstscream \
        cargo doc
        
    - name: Clippy
      run: |
        cd gstscream \
        cargo clippy
    - name: Run tests
      run: |
        cd gstscream \
        cargo test
